dataset:
  dataset_id: "saferlhf-v/BeaverTails-V"
  split: "evaluation"

model:
  key: "qwen2-vl-7b-instruct"

generation:
  max_new_tokens: 81920

runtime:
  batch_size: 32

output_dir: "/projects/u6lm/ns1324/msc_thesis/results/benchmarking/beavertails-v"